apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHk1MDAuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIllXNXJhWFE2UVc1cmFYUkFOVGs9IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
